#!/usr/bin/python2.7

sleep = 5

import metrics_cpu_task_time
import metrics_load_average

from conf import *
from requests.auth import HTTPBasicAuth
import os
import requests
import socket
import time

host = socket.gethostname()

while True:

	data = []
	data = data + metrics_cpu_task_time.metrics()
	data = data + metrics_load_average.metrics()

	for i, d in enumerate(data):
		measurement = d['measurement']
		line = measurement
		tags = d['tags']
		if len(tags) > 0:
			tags = ["{}={}".format(k, v) for k, v in tags.items()]
			tags = ",".join(tags)
			line = line + ',' + tags
		fields = d['fields']
		fields = ["{}={}".format(k, str(v)) for k, v in fields.items()]
		fields = ",".join(fields)
		line = line + ' ' + fields
		data[i] = line

	data = "\n".join(data)

	url='http://{}:{}/write?consistency=&db={}&precision=&rp='.format(dbhost, dbport, dbname)
	r = requests.post(
		url=url,
		auth=HTTPBasicAuth(dbuser, dbpass),
		data=data,
	)
	# expected 204 - no content
	# print r.status_code

	time.sleep(sleep)
