#!/usr/bin/python2.7

sleep = 10

import metrics_cpu_task_time
import metrics_load_average

import socket
import sys
import time

from Monitoring import Monitoring

if len(sys.argv) < 1 + 1:
	print 'Usage: ' + sys.argv[0] + ' <conf>'
	sys.exit(1)

conffile = sys.argv[1]

m = Monitoring(conffile)

while True:

	data = metrics_cpu_task_time.metrics()
	print data
	m.collect_many(data)

	data = metrics_load_average.metrics()
	print data
	m.collect_many(data)

	m.send()

	time.sleep(sleep)
