#!/usr/bin/python2.7

sleep=20

import metrics_container_status
import metrics_cpu_exe_time

import socket
import sys
import time

from Monitoring import Monitoring

if len(sys.argv) < 1 + 1:
	print 'Usage: ' + sys.argv[0] + ' <conf>'
	sys.exit(1)

conffile = sys.argv[1]

m = Monitoring(conffile)

# make sure only one instance runs
try:
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.bind(('127.0.0.1', 12345))
except:
	sys.exit()

exe_prev = {}
while True:

	data = metrics_container_status.metrics()
	m.collect_many(data)

	data = metrics_cpu_exe_time.metrics()
	m.collect_many(data)

	m.send()

	time.sleep(sleep)
